ARG RUBY_VERSION=2.5
FROM ruby:${RUBY_VERSION}

RUN mkdir /src
WORKDIR /src

COPY Gemfile Gemfile
COPY conjur-policy-parser.gemspec conjur-policy-parser.gemspec
COPY lib/conjur-policy-parser-version.rb lib/conjur-policy-parser-version.rb

# Make sure only one version of bundler is available
RUN gem uninstall bundler -i /usr/local/lib/ruby/gems/${RUBY_VERSION} bundler || true && \
  gem uninstall bundler -aIx || true && \
  gem install bundler -v 1.11.2 && \
  bundle install
